version: '3'

services:

  db:
    container_name: product_reviewer_db
    hostname: pg.product-reviewer
    image: postgres:14-alpine
    environment:
      DATABASE_HOST: '127.0.0.1'
      PGUSER: 'postgres'
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "unidunite"
      POSTGRES_CONNECTION_STRING: "jdbc:postgresql://127.0.0.1:5432/postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - product-reviewer

  pgadmin:
    container_name: product_reviewer_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - product-reviewer


networks:
  product-reviewer:
    driver: bridge