spring:
  datasource:
    username: ${DEV_DB_USER:postgres}
    url: ${DEV_DB_CONNECTION_STRING:jdbc:postgresql://127.0.0.1:5432/postgres}
    password: ${DEV_DB_PASSWORD:unidunite}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
