spring:
  datasource:
    username: ${DB_USER}
    url: ${DB_CONNECTION_STRING}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": false
    hibernate:
      ddl-auto: update
    show-sql: false
